# Generated by Django 3.0.6 on 2020-05-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afterlockdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='call_id',
            field=models.CharField(default='Afhb45t', max_length=160),
            preserve_default=False,
        ),
    ]
