# Generated by Django 3.0.6 on 2020-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='covid19 latest', max_length=200000000)),
                ('author', models.CharField(blank=True, max_length=200000000, null=True)),
                ('title', models.CharField(max_length=200000000)),
                ('content', models.CharField(blank=True, max_length=200000000, null=True)),
                ('url', models.CharField(max_length=200000000)),
                ('urlToImage', models.CharField(blank=True, max_length=200000000, null=True)),
                ('publishedAt', models.CharField(max_length=200000000)),
            ],
        ),
    ]
